site_name: "Zeppelin 0.7.2 中文文档"
site_url: http://zeppelin.apachecn.org
site_description: "Zeppelin 0.7.2 中文文档"
site_author: ApacheCN Team

repo_url: https://github.com/apachecn/zeppelin-doc-zh
repo_name: zeppelin-doc-zh

use_directory_urls: true
nav:
- "Zeppelin 0.7.2 中文文档" : "README.md"
- "快速入门" : "1.md"
- "什么是Apache Zeppelin?" : "2.md"
- "安装" : "3.md"
- "配置" : "4.md"
- "探索Apache Zeppelin UI" : "5.md"
- "教程" : "6.md"
- "动态表单" : "7.md"
- "发表你的段落" : "8.md"
- "自定义Zeppelin主页" : "9.md"
- "升级Zeppelin版本" : "10.md"
- "从源码编译" : "11.md"
- "使用Flink和Spark Clusters安装Zeppelin教程" : "12.md"
- "解释器" : "13.md"
- "概述" : "14.md"
- "解释器安装" : "15.md"
- "解释器依赖管理" : "16.md"
- "解释器的模拟用户" : "17.md"
- "解释员执行Hook（实验）" : "18.md"
- "Alluxio 解释器" : "19.md"
- "Beam 解释器" : "20.md"
- "BigQuery 解释器" : "21.md"
- "Cassandra CQL 解释器" : "22.md"
- "Elasticsearch 解释器" : "23.md"
- "Flink 解释器" : "24.md"
- "Geode/Gemfire OQL 解释器" : "25.md"
- "HBase Shell 解释器" : "26.md"
- "HDFS文件系统 解释器" : "27.md"
- "Hive 解释器" : "28.md"
- "Ignite 解释器" : "29.md"
- "JDBC通用 解释器" : "30.md"
- "Kylin 解释器" : "31.md"
- "Lens 解释器" : "32.md"
- "Livy 解释器" : "33.md"
- "Markdown 解释器" : "34.md"
- "Pig 解释器" : "35.md"
- "PostgreSQL, HAWQ 解释器" : "36.md"
- "Python 2＆3解释器" : "37.md"
- "R 解释器" : "38.md"
- "Scalding 解释器" : "39.md"
- "Scio 解释器" : "40.md"
- "Shell 解释器" : "41.md"
- "Spark 解释器" : "42.md"
- "系统显示" : "43.md"
- "系统基本显示" : "44.md"
- "后端Angular API" : "45.md"
- "前端Angular API" : "46.md"
- "更多" : "47.md"
- "笔记本存储" : "48.md"
- "REST API" : "49.md"
- "解释器 API" : "50.md"
- "笔记本 API" : "51.md"
- "笔记本资源 API" : "52.md"
- "配置 API" : "53.md"
- "凭据 API" : "54.md"
- "Helium API" : "55.md"
- "Security ( 安全 )" : "56.md"
- "Shiro 授权" : "57.md"
- "笔记本 授权" : "58.md"
- "数据源 授权" : "59.md"
- "Helium 授权" : "60.md"
- "Advanced ( 高级 )" : "61.md"
- "Zeppelin on Vagrant VM ( Zeppelin 在 Vagrant 虚拟机上 )" : "62.md"
- "Zeppelin on Spark Cluster Mode( Spark 集群模式下的 Zeppelin )" : "63.md"
- "Zeppelin on CDH ( Zeppelin 在 CDH 上 )" : "64.md"
- "Contibute ( 贡献 )" : "65.md"
- "Writing a New Interpreter ( 写一个新的解释器 )" : "66.md"
- "Writing a new Visualization (Experimental) ( 编写新的可视化（实验） )" : "67.md"
- "Writing a new Application (Experimental) ( 写一个新的应用程序( 实验 ) )" : "68.md"
- "Contributing to Apache Zeppelin ( Code ) ( 向 Apache Zeppelin 贡献( 代码 ) )" : "69.md"
- "Contributing to Apache Zeppelin ( Website ) ( 向 Apache Zeppelin 贡献(website) )" : "70.md"

theme:
  name: mkdocs
  custom_dir: 'custom_theme/'
  
  # 404 page
  static_templates:
    - 404.md
  
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  
  # Default values, taken from mkdocs_theme.yml
  language: 'zh'
  feature:
    tabs: true
  palette:
    primary: 'Indigo'
    accent: 'Indigo'
  font: false
  favicon: assets/images/favicon.png
  logo: 
    icon: "\uE80C"